---
- name: Create Arista Vlans
  hosts: arista

  tasks:
   - name: Create BLUE VLAN
     eos_vlan: name=BLUE vlanid=100
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https

   - name: Create RED VLAN
     eos_vlan: name=RED vlanid=200
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https                          

   - name: Create GREEN VLAN
     eos_vlan: name=GREEN vlanid=300
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https
