---

# Use Ansible to restore your 'primary Ethernet interface' back to the 
# following state:
#
# description:            <none>
# switchport mode:        access
# access VLAN:            1
# trunk allowed VLANs:    all
#
# Also use Ansible to remove the three VLANs that you configured

- name: Arista-Ansible Exercise4
  hosts: arista

  tasks:
   - name: Remove Trunk
     eos_switchport: name=Ethernet3 mode=access access_vlan=1 trunk_allowed_vlans=1-4094
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https

   - name: Reset Description
     eos_interface: name=Ethernet3 description=""
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https

   - name: Remove Vlans
     eos_vlan: name={{ item.name }} vlanid={{ item.vlanid }} state=absent
         username={{ eapi_username }}
         password={{ eapi_password }}
         host={{ eapi_hostname }}
         port={{ eapi_port }}
         transport=https

     with_items:
       - {name: DR1, vlanid: 441}
       - {name: DR2, vlanid: 442}
       - {name: DR3, vlanid: 443}
