---
# Use the cisco_file_transfer.py module to transfer a small file to the Cisco 
# # pynet-rtr1 router.
#
- name: Ansible-Cisco File Transfer
  hosts: cisco 
  gather_facts: False

  tasks:
  - name: File Transfer
    cisco_file_transfer:
          source_file="/home/drobb/cisco-logging.txt" 
          dest_file="cisco-logging.txt"
          overwrite=true
          enable_scp=true
          hosts={{ host }}
          port={{ port }}
          username={{ username }}
          password={{ password }}
